### ISSUE TITLE
Using hobby-0 is not possible ::  cannot unmarshal number 0.5 into Go struct field ClusterDetail.memory of type int

### ISSUE THREAD

**Issue by oDevArc** [CrunchyData/terraform-provider-crunchybridge#8]
Heloo

I have this error when trying to create/update a PGCluster as a hobby-0 type: Error: error unmarshaling response body (cluster detail): json: cannot unmarshal number 0.5 into Go struct field ClusterDetail.memory of type int

It seems that it is just a bad cast in Golang 

does somebody can add correction to handle float instead of int ?

**Comment by fermentfan** [comment]
Ouuf same problem here

**Comment by wilybrace** [comment]
Resolved in release v0.2.0, available via Terraform registry.
